### ISSUE TITLE
State Copy constructor

### ISSUE THREAD

**Issue by david-nader** [YoussefAwny/Connect_Four_AI#3]
Copy constructor should also copy all class variables
```c++
last_move
num_empty_cells
```

**Comment by KirollosTadros** [comment]
In what line of the code is this bug?

**Comment by KirollosTadros** [comment]
@YoussefAwny  check this issue because changing state.cpp file while you're working on it will make a merge conflict.

**Comment by YoussefAwny** [comment]
done and I will push it now
